paths:
  train: "${hydra:runtime.cwd}/tabular_src/test/testdata/adult.csv"
  test:
  output: "${hydra:runtime.cwd}/results"
  result: "${hydra:runtime.cwd}/results/exp_3"

columns:
  categorical_columns: ['workclass', 'fnlwgt', 'education', 'marital.status', 'occupation', 'relationship',
                        'race', 'sex', 'native.country']
  text_columns:
  keep_columns:
  sensitive_columns: ['race', 'sex']
  target_label: 'income'

process:
  exp_id: 'lightgbm'
  memory_reduce: True
  infer_datatype: True
  test_ratio: 0.2
  seed: 33
  task: 'classification'
  verbose: False
  surrogate_model: False
  only_surrogate: False

feature_selection:
  auto: False
  estimator: 'lightgbm'
  n_features: 9
  multi_colinear_threshold: 0.6

data_validation:
  data_drift: False
  data_integrity: False
  save_html: False

defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

model:
  surrogate_algorithm: 'random_forest'
  algorithm: ['lightgbm']
  ensemble: True
  ensemble_type: 'stack'
  cv_fold: 4
  iteration: 30
  prob_thresh: 0.4
  tuning: False
  pca: False
  calibrate: True
  feature_importance: False
  fairness: True

hyperparams:
  - lightgbm:
  - xgboost:
  - catboost:
  - dt:
  - logistic_regression:
  - linear_regession:
  - svm:
  - rf:
  - knn:
  - gbc:
